Make solution compile in VS
Add FSharp.Core package reference so that solution compiles
without errors in Visual Studio.

Errors were:
```
D:\Projects\work\FX\src\FX.Tests\LimitOrders.cs(5,17): error CS0234: The type or namespace name 'FSharp' does not exist in the namespace
 'Microsoft' (are you missing an assembly reference?) [D:\Projects\work\FX\src\FX.Tests\FX.Tests.csproj]
D:\Projects\work\FX\src\FX.Tests\LimitOrders.cs(16,25): error CS0246: The type or namespace name 'FSharpOption<>' could not be found (ar
e you missing a using directive or an assembly reference?) [D:\Projects\work\FX\src\FX.Tests\FX.Tests.csproj]
```